version: '3.7'

services:
  app:
    build:
      context: .
    volumes:
      - .:/workspace
    command: sleep infinity  # Keeps the container running
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpassword
      - MYSQL_DATABASE=medtech_db

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: medtech_db
    ports:
      - "3306:3306"
